// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSUJ4nWwkZUbZM0haLSnnCwFjb8WDDGRU',
    appId: '1:113440172204:web:609dd4add00cde96225709',
    messagingSenderId: '113440172204',
    projectId: 'app-bioskop-9543a',
    authDomain: 'app-bioskop-9543a.firebaseapp.com',
    storageBucket: 'app-bioskop-9543a.appspot.com',
    measurementId: 'G-VW8SLT0FZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH_nqRA6Z9VymnNzQ1oBwqCJltsS-LkMM',
    appId: '1:113440172204:android:3b803294c5e899c8225709',
    messagingSenderId: '113440172204',
    projectId: 'app-bioskop-9543a',
    storageBucket: 'app-bioskop-9543a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd7Ow3zpDHG42ApxbCiD5cpzzV1CeFb20',
    appId: '1:113440172204:ios:cb30cb29f5c93abd225709',
    messagingSenderId: '113440172204',
    projectId: 'app-bioskop-9543a',
    storageBucket: 'app-bioskop-9543a.appspot.com',
    iosClientId: '113440172204-dr4idhctl0mohuubhp9a0p7qehcv87b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkBioskop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd7Ow3zpDHG42ApxbCiD5cpzzV1CeFb20',
    appId: '1:113440172204:ios:956506ac213eb2e3225709',
    messagingSenderId: '113440172204',
    projectId: 'app-bioskop-9543a',
    storageBucket: 'app-bioskop-9543a.appspot.com',
    iosClientId: '113440172204-1qo6g8c6pjt0pcj7hkncdfp67cqnnmbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkBioskop.RunnerTests',
  );
}
